apiVersion: v1
kind: Pod
metadata:
  name: state-manager
  labels:
    app: state-manager
spec:
  containers:
  - name: state-manager
    image: bacterie-tp-state-manager:latest
    imagePullPolicy: Never
    volumeMounts:
    - name: state-storage
      mountPath: /data
  volumes:
  - name: state-storage
    persistentVolumeClaim:
      claimName: bacterie-state-pvc
